makeplane/docs

README.md
src/components/Code.jsx
src/components/Footer.jsx
src/components/MobileNavigation.jsx
src/components/Navigation.jsx
src/components/Resources.jsx
src/lib/constants.js
src/pages/index.mdx
src/pages/integrations.mdx
src/pages/modules.mdx
src/pages/self-hosting.mdx

This PR fixes a lot of typos and adds the `Edit on GitHub` button.

Fix typos and add Edit on GitHub

---

src/components/Footer.jsx

quick and dirty fix of "edit on github" in light mode

---

src/pages/self-hosting.mdx

docs: update self hosting docs to get correct instance IP

docs: update self hosting docs to get correct instance IP

---

src/pages/self-hosting.md

docs: update self hosting.md with domain name for setup script

docs: update self hosting.md with domain name for setup script

---

src/components/Layout.jsx
src/pages/projects.md
src/pages/workspaces.md

fix: language

---

src/pages/self-hosting.md

docs: update self hosting setup

docs: update self hosting setup

---

src/pages/self-hosting.md

docs: remove -d flag comments

---

src/pages/self-hosting.md

docs: self host add depth to clone command

docs: self host add depth to clone command

---

src/pages/self-hosting.md

docs: self hosting docker compose command

docs: self hosting docker compose command

---

next.config.js

This PR contains the fix for the self-hosting page 404 issue

fix: self hosting url

---

api-reference/cycle-issue/list-cycle-issues.mdx
api-reference/cycle/list-cycles.mdx
api-reference/inbox-issue/list-inbox-issues.mdx
api-reference/issue-activity/list-issue-activities.mdx
api-reference/issue-comment/list-issue-comments.mdx
api-reference/issue/list-issues.mdx
api-reference/label/list-labels.mdx
api-reference/link/list-links.mdx
api-reference/module-issue/list-module-issues.mdx
api-reference/module/list-modules.mdx
api-reference/project/list-projects.mdx
api-reference/state/list-states.mdx
mint.json

This PR contains the updated titles for the sidebar items in the API reference.

API reference sidebar titles update

---

introduction/home.mdx

Remove an unnecessary '-v2' from the docs repository.

Correct path to CONTRIBUTING.md

---

docs/devices/mobile.mdx

* Added create project and pages info
* minor edits

Added create project and pages info

---

docs/core-concepts/cycles.mdx
src/css/custom.css

- Revamped the cycle page and updated all images
- new image borders
- Added information about Cycle progress charts

Cycle progress charts

---

src/css/custom.css

This PR aims to make the sidebar centre aligned on larger screens, without changing the layout for smaller ones.

Centre aligning the sidebar on larger screens

---

docs/templates/project-templates.mdx
docs/templates/work-item-templates.mdx

Updated cross references in Templates

---

docs/core-concepts/issues/overview.mdx
docusaurus.config.ts

Added Plausible analytics and SQL supported file upload

---

vercel.json

Fixed redirects for importers

---

docs/intake/intake-email.mdx

Intake Email for self-hosted instances

---

docs/core-concepts/pages/nested-pages.mdx
sidebars.ts

Nested Pages

---

.github/workflows/docs-to-vector.yml

Added github action to notify Plane-Pi about new commit in this repo.

chore: GH Action added

---

docs/core-concepts/analytics.mdx
docs/core-concepts/projects/overview.mdx

Updated Analytics page

---

docs/core-concepts/analytics.mdx
docs/core-concepts/issues/overview.mdx
docs/core-concepts/issues/properties.mdx
docs/core-concepts/pages/overview.mdx
docs/core-concepts/projects/overview.mdx
docs/core-concepts/workspaces/members.mdx
docs/customers.mdx
docs/devices/mobile.mdx

Multiple updates - New Analytics and other minor fixes

---

docusaurus.config.ts
package.json
yarn.lock

- Updated Google Tag Manger for traffic monitoring

chore: adding google tag manger for tracking
